### ISSUE TITLE
Benchmark fails almost immediately on training start with OOM error

### ISSUE THREAD

**Issue by Xaenalt** [AICoE/benchmarks-tekton#8]
When attempting the benchmark, I was hitting an almost immediate OOM error. This is despite nodes having more than enough free memory to satisfy the 12Gb limit

![image](https://user-images.githubusercontent.com/8479010/83650049-e76af000-a585-11ea-8061-47a60b41c0bd.png)
Almost immediately after this, it fails with either return code 137 or 255, the pod listing OOMKilled as the reason

**Comment by Xaenalt** [comment]
As a note, the pod is only consuming ~3-4Gb of RAM at the time it exits as well

**Comment by Xaenalt** [comment]
```
    - restartCount: 0
      started: false
      ready: false
      name: step-run
      state:
        terminated:
          exitCode: 255
          reason: OOMKilled
          message: >-
            [{"key":"StartedAt","value":"2020-06-02T19:58:04Z","resourceRef":{}}]
          startedAt: '2020-06-02T19:57:56Z'
          finishedAt: '2020-06-02T20:01:02Z'
          containerID: >-
            cri-o://6f06a17d4da67d79f47359bece32163709441544350486a1ea3eb9bca04ac8c8
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/mlperf/tfc-benchmark@sha256:7a78f8322d30a34f1a4da53833728a91de887c1ccc21f0cea77c0457974063ca
      image: >-
        image-registry.openshift-image-registry.svc:5000/mlperf/tfc-benchmark:cpu
      lastState: {}
      containerID: 'cri-o://6f06a17d4da67d79f47359bece32163709441544350486a1ea3eb9bca04ac8c8'

```
